let ItemGeneration = new ItemGenerate()
ItemGeneration.addItem(ItemID.aquatiteingot, 1, {max: 3})
ItemGeneration.addItem(ItemID.aeriteingot, .6, {max: 6})
ItemGeneration.addItem(ItemID.aeressence, .4, {max: 5})
ItemGeneration.addItem(ItemID.starsword, .5, {max: 1})
