Item.addCreativeGroup("terra_armor", "Земля", [
	ItemID.terrahelmet,
	ItemID.terrachestplate,
	ItemID.terraleggings,
	ItemID.terraboots,
	ItemID.terrasword,
	ItemID.terrapickaxe,
	ItemID.terraaxe,
	ItemID.terrashovel
]);
Item.addCreativeGroup("ignis_armor", "Огонь", [
	ItemID.ignishelmet,
	ItemID.ignischestplate,
	ItemID.ignisleggings,
	ItemID.ignisboots,
	ItemID.ignissword,
	ItemID.ignispickaxe,
	ItemID.ignisaxe,
	ItemID.ignisshovel
]);
Item.addCreativeGroup("aer_armor", "Воздух", [
	ItemID.aerhelmet,
	ItemID.aerchestplate,
	ItemID.aerleggings,
	ItemID.aerboots,
	ItemID.aersword,
	ItemID.aerpickaxe,
	ItemID.aeraxe,
	ItemID.aershovel
]);
Item.addCreativeGroup("aqua_armor", "Вода", [
	ItemID.aquahelmet,
	ItemID.aquachestplate,
	ItemID.aqualeggings,
	ItemID.aquaboots,
	ItemID.aquasword,
	ItemID.aquapickaxe,
	ItemID.aquaaxe,
	ItemID.aquashovel
]);
Item.addCreativeGroup("comet_armor", "Кометит", [
	ItemID.cometitehelmet,
	ItemID.cometitechestplate,
	ItemID.cometiteleggings,
	ItemID.cometiteboots,
	ItemID.cometitesword,
	ItemID.cometitepickaxe,
	ItemID.cometiteaxe,
	ItemID.cometiteshovel
]);
Item.addCreativeGroup("holly_armor", "Святое", [
	ItemID.hollyhelmet,
	ItemID.hollychestplate,
	ItemID.hollyleggings,
	ItemID.hollyboots,
	ItemID.hollysword,
	ItemID.exalibur,
	ItemID.hollypickaxe,
	ItemID.hollyaxe,
	ItemID.hollyshovel
]);
Item.addCreativeGroup("minecraft_armor", "Майнкрафт", [
	ItemID.grandminecrafthelmet,
	ItemID.grandminecraftchestplate,
	ItemID.grandminecraftleggings,
	ItemID.grandminecraftboots,
	ItemID.grandminecraftsword,
	ItemID.grandminecraftpickaxe,
	ItemID.grandminecraftaxe,
	ItemID.grandminecraftshovel
]);
Item.addCreativeGroup("kraken_armor", "Кракен", [
	ItemID.krackenhelmet,
	ItemID.krackenchestplate,
	ItemID.krackenleggings,
	ItemID.krackenboots,
	ItemID.krackensword,
	ItemID.krackenkatana,
	ItemID.krackenblade,
	ItemID.krackenpickaxe,
	ItemID.krackenaxe,
	ItemID.krackenshovel
]);
Item.addCreativeGroup("paladium_armor", "Паладиум", [
	ItemID.palladiumhelmet,
	ItemID.palladiumchestplate,
	ItemID.palladiumleggings,
	ItemID.palladiumboots,
	ItemID.palladiumsword,
	ItemID.palladiumpickaxe,
	ItemID.palladiumaxe,
	ItemID.palladiumshovel
]);
Item.addCreativeGroup("horngod_armor", "Рогатый бог", [
	ItemID.horngodhelmet,
	ItemID.horngodchestplate,
	ItemID.horngodleggings,
	ItemID.horngodboots,
	ItemID.horngodsword,
	ItemID.horngodpickaxe,
	ItemID.horngodaxe,
	ItemID.horngodshovel
]);
Item.addCreativeGroup("astral_armor", "Астрал", [
	ItemID.astralhelmet,
	ItemID.astralchestplate,
	ItemID.astralleggings,
	ItemID.astralboots,
	ItemID.astralsword,
	ItemID.astralpickaxe,
	ItemID.astralaxe,
	ItemID.astralshovel
]);
Item.addCreativeGroup("chaos_armor", "Хаос", [
	ItemID.chaoshelmet,
	ItemID.chaoschestplate,
	ItemID.chaosleggings,
	ItemID.chaosboots,
	ItemID.chaossword,
	ItemID.chaospickaxe,
	ItemID.chaosaxe,
	ItemID.chaosshovel
]);
Item.addCreativeGroup("omicron_armor", "Омикрон", [
	ItemID.omikronhelmet,
	ItemID.omikronchestplate,
	ItemID.omikronleggings,
	ItemID.omikronboots,
	ItemID.omikronsword,
	ItemID.omikronpickaxe,
	ItemID.omikronaxe,
	ItemID.omikronshovel
]);
Item.addCreativeGroup("venomus_armor", "Веномус", [
	ItemID.venomushelmet,
	ItemID.venomuschestplate,
	ItemID.venomusleggings,
	ItemID.venomusboots,
	ItemID.venomussword,
	ItemID.venomuspickaxe,
	ItemID.venomusaxe,
	ItemID.venomusshovel
]);
Item.addCreativeGroup("meow_armor", "Мяу", [
	ItemID.meowhelmet,
	ItemID.meowchestplate,
	ItemID.meowleggings,
	ItemID.meowboots,
	ItemID.meowsword,
	ItemID.meowmere,
	ItemID.murrrsama,
	ItemID.meowpickaxe,
	ItemID.meowaxe,
	ItemID.meowshovel
]);
Item.addCreativeGroup("florite_armor", "Флорит", [
	ItemID.floritehelmet,
	ItemID.floritechestplate,
	ItemID.floriteleggings,
	ItemID.floriteboots,
	ItemID.floritesword,
	ItemID.floritepickaxe,
	ItemID.floriteaxe,
	ItemID.floriteshovel
]);
Item.addCreativeGroup("galaxite_armor", "Галаксит", [
	ItemID.galaxitehelmet,
	ItemID.galaxitechestplate,
	ItemID.galaxiteleggings,
	ItemID.galaxiteboots,
	ItemID.galaxitesword,
	ItemID.galaxitepickaxe,
	ItemID.galaxiteaxe,
	ItemID.galaxiteshovel
]);
Item.addCreativeGroup("goldy_armor", "Злотоносная", [
	ItemID.goldyhelmet,
	ItemID.goldychestplate,
	ItemID.goldyleggings,
	ItemID.goldyboots,
	ItemID.goldysword,
	ItemID.goldypickaxe,
	ItemID.goldyaxe,
	ItemID.goldyshovel
]);
Item.addCreativeGroup("shadowspec_armor", "Шедоуспех", [
	ItemID.shadowspechelmet,
	ItemID.shadowspecchestplate,
	ItemID.shadowspecleggings,
	ItemID.shadowspecboots,
	ItemID.shadowspecsword,
	ItemID.shadowspecpickaxe,
	ItemID.shadowspecaxe,
	ItemID.shadowspecshovel
]);
Item.addCreativeGroup("azatot_armor", "Азатот", [
	ItemID.azatothelmet,
	ItemID.azatotchestplate,
	ItemID.azatotleggings,
	ItemID.azatotboots,
	ItemID.azatotsword,
	ItemID.azatotpickaxe,
	ItemID.azatotaxe,
	ItemID.azatotshovel
]);
Item.addCreativeGroup("chtulhu_armor", "Ктулху", [
	ItemID.chtulhuhelmet,
	ItemID.chtulhuchestplate,
	ItemID.chtulhuleggings,
	ItemID.chtulhuboots,
	ItemID.chtulhusword,
	ItemID.chtulhupickaxe,
	ItemID.chtulhuaxe,
	ItemID.chtulhushovel
]);
Item.addCreativeGroup("ark_armor", "Арк", [
	ItemID.ArkHelmet,
	ItemID.ArkChestplate,
	ItemID.ArkLeggings,
	ItemID.ArkBoots
]);
Item.addCreativeGroup("shard", "Осколки", [
	ItemID.livingshard,
	ItemID.evilfragment,
	ItemID.energyfragment,
	ItemID.coldfragment,
	ItemID.fragmentoftruncatissoul,
	ItemID.millionfragment,
	ItemID.stardust,
	ItemID.blackmagicdust,
	ItemID.calamitydust,
	ItemID.azatotdust
]);
Item.addCreativeGroup("decor_block", "Декоративные блоки", [
	BlockID.cloud,
	BlockID.cometgrass,
	BlockID.cometdirt,
	BlockID.steb,
	BlockID.ship,
	BlockID.rose,
	BlockID.heartblock,
	BlockID.azatotmateria,
	BlockID.azatotbricks,
	BlockID.azatotaltar,
	BlockID.azatotaltaractivated,
	BlockID.azatotaltaroff,
	BlockID.astralyellow,
	BlockID.astralpink,
	BlockID.astralmid
]);
Item.addCreativeGroup("ore", "Руды", [
	BlockID.aeriteore,
	BlockID.aquatiteore,
	BlockID.ignisusore,
	BlockID.ignisusnetherore,
	BlockID.territeore,
	BlockID.cometiteore,
	BlockID.heartore,
	BlockID.hollyore,
	BlockID.astralore,
	BlockID.chaosore,
	BlockID.floriteore,
	BlockID.goldyore,
	BlockID.depthore,
]);
Item.addCreativeGroup("armor_magic", "Магическая броня", [
	ItemID.germesboots,
	ItemID.firerisboots,
	ItemID.gfboots,
	ItemID.ugfboots
]);
Item.addCreativeGroup("core", "Ядра", [
	ItemID.aercore,
	ItemID.aquacore,
	ItemID.igniscore,
	ItemID.terracore,
	ItemID.elementalcore
]);
Item.addCreativeGroup("essence", "Эссенции", [
	ItemID.aeressence,
	ItemID.aquaessence,
	ItemID.ignisessence,
	ItemID.terraessence,
	ItemID.profanedessence,
	ItemID.calamityessence,
]);
Item.addCreativeGroup("teleport", "Телепортеры", [
	ItemID.overworld,
	ItemID.azatotshears,
	ItemID.astralshears
]);
Item.addCreativeGroup("summon boss", "Призыв босcов", [
	ItemID.Hollybot,
	ItemID.Naida,
	ItemID.Phantom,
	ItemID.Kracken,
	ItemID.ElementalGuardian,
	ItemID.ArsenalCreator,
	ItemID.CaptainOfArkOfTheCosmos,
	ItemID.Paladin,
	ItemID.VenomCultist,
	ItemID.Hatur,
	ItemID.CiciditDea,
	ItemID.Seederus,
	ItemID.Ekatebrina,
	ItemID.Calamitatis,
	ItemID.VerumDevourerDeorum,
	ItemID.Truncatis,
	ItemID.VerumCalamitatis,
	ItemID.Zeus,
	ItemID.Kron,
	ItemID.Chtulhu,
	ItemID.Ark,
	ItemID.VerumPtah
]);
Item.addCreativeGroup("food", "Сердца", [
	ItemID.lifecrystal,
	ItemID.fireheart,
	ItemID.elementalheart,
]);
Item.addCreativeGroup("ingot", "Слитки", [
	ItemID.aeriteingot,
	ItemID.territeingot,
	ItemID.ignisusingot,
	ItemID.aquatiteingot,
	ItemID.cometiteingot,
	ItemID.hollyingot,
	ItemID.elementalingot,
	ItemID.cosmicsingularity,
	ItemID.krackeningot,
	ItemID.cosmiliteingot,
	ItemID.omikroneingot,
	ItemID.heartingot,
	ItemID.palladiumingot,
	ItemID.astralingot,
	ItemID.chaosingot,
	ItemID.venomusingot,
	ItemID.meowingot,
	ItemID.floriteingot,
	ItemID.goldyingot,
	ItemID.shadowspecingot,
	ItemID.azatotingot,
	ItemID.depthingot,
	ItemID.galaxiteingot
]);
Item.addCreativeGroup("sword", "Оружие", [
	ItemID.starsword,
	ItemID.enchantedsword,
	ItemID.brokenherosword,
	ItemID.ancientark,
	ItemID.trueexalibur,
	ItemID.herosword,
	ItemID.trueancientark,
	ItemID.elementalark,
	ItemID.biomesword,
	ItemID.truebiomesword,
	ItemID.omegabiomesword,
	ItemID.muramasa,
	ItemID.murasama,
	ItemID.rootenbroadsword,
	ItemID.taigasword,
	ItemID.grandbiomesword,
	ItemID.elementalsword,
	ItemID.ArsenalGuardian,
	ItemID.swordofDNil,
	ItemID.ahalalui,
	ItemID.kartzon,
	ItemID.krackensh,
	ItemID.truekrackensh,
	ItemID.astral,
	ItemID.heavensword,
	ItemID.jackbomb,
	ItemID.rdrill,
	ItemID.earther,
	ItemID.starevil,
	ItemID.hollycollider,
	ItemID.heatedamputation,
	ItemID.ryusukesword,
	ItemID.horsemansword,
	ItemID.northpole,
	ItemID.huskentrophy,
	ItemID.dpickaxe,
	ItemID.exelsus,
	ItemID.dragonevil,
	ItemID.profanedtrident,
	ItemID.burningsky,
	ItemID.galaxia,
	ItemID.Ark_of_the_Cosmos,
	ItemID.Omikrone_Ark_of_the_Cosmos,
	ItemID.earth,
	ItemID.animus,
	ItemID.dragondestroy,
	ItemID.paladinhammer,
	ItemID.redsun,
	ItemID.azatot,
	ItemID.crystalpickaxe,
	ItemID.truepaladinhammer,
	ItemID.lightningbolt,
	ItemID.kronsword,
	ItemID.krslsword,
	ItemID.oahusword,
	ItemID.ptahstaff,
	ItemID.firefall,
	ItemID.verumazatot,
	ItemID.otherplanet,
	ItemID.starkiller,
	ItemID.ankhsword,
	ItemID.True_Ark_of_the_Cosmos,
	ItemID.TinEverestraSword,
	ItemID.HellSword,
	ItemID.EndSword,
	ItemID.AzatothSword,
	ItemID.AstralSworda,
	ItemID.MultiverseSword,
]);
Item.addCreativeGroup("books", "Книги", [
	ItemID.hollybotbook,
	ItemID.naidabook,
	ItemID.krakenbook,
	ItemID.elementalguardianbook,
	ItemID.arsenalguardianbook,
	ItemID.arsenalcreatorbook,
	ItemID.captainofarkofthecosmos,
	ItemID.devourerdeorumbook,
	ItemID.seederusbook,
	ItemID.ekatebrinebook,
	ItemID.calamitatisbook,
	ItemID.ciciditdeabook,
	ItemID.venomkultistbook,
	ItemID.haturbook,
	ItemID.verumdevourerdeorumbook,
	ItemID.truncatisbook,
	ItemID.verumcalamitatisbook,
	ItemID.azatotbook,
	ItemID.chtulhubook,
	ItemID.arktludumthnbook,
	ItemID.arktludumthnbooktwo,
	ItemID.arktludumthnbookthree,
	ItemID.arktludumthnbookfour,
	ItemID.arktludumthnbookfive,
	ItemID.arktludumthnbooksix,
	ItemID.arktludumthnbookseven,
	ItemID.arktludumthnbookeight,
	ItemID.arktludumthnbooknine,
	ItemID.arktludumthnbookseederus,
	ItemID.arktludumthnbookcalamitatis,
	ItemID.arktludumthnbookvenomcultist,
	ItemID.arktludumthnbookhatur,
	ItemID.arktludumthnbookciciditdea,
	ItemID.arktludumthnbookverumdevourerdeorum,
	ItemID.arktludumthnbooktruncatis,
	ItemID.arktludumthnbookverumcalamitatis,
	ItemID.arktludumthnbookazatot,
	ItemID.arktludumthnbookchtulhu,
	ItemID.arktludumthnbookfinal
]);